apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gitops-nginx
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gitops-nginx
  template:
    metadata:
      labels:
        app: gitops-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1
        ports:
        - containerPort: 80
